# Generated by Django 3.1.5 on 2021-03-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
                ('evolutions', models.ManyToManyField(related_name='_pokemon_evolutions_+', to='Pokedex.Pokemon')),
                ('types', models.ManyToManyField(to='Pokedex.Type')),
            ],
        ),
    ]
