# Generated by Django 3.1.5 on 2021-03-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokedex', '0002_auto_20210320_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='number',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
