# Generated by Django 3.1.5 on 2021-03-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokedex', '0003_auto_20210320_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='evolutions',
            field=models.ManyToManyField(to='Pokedex.Pokemon'),
        ),
    ]
